# ############
# # 1. style 
# ############
flake8:
  image: mambaorg/micromamba
  tags:
    - docker
  script:
    - micromamba install -y flake8
    - flake8 cmcmultimodal

# ############
# # 2. test 
# ############
# test:
#   image: mambaorg/micromamba
#   tags:
#     - docker
#   script:
#     - bash ./.ci/unit_tests.sh
